# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alliance_member.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'alliance_member.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61lliance_member.proto\x12\x35\x63om.ankama.dofus.server.game.protocol.alliance.member\x1a\x0c\x63ommon.proto\"1\n\x19\x41llianceInvitationRequest\x12\x14\n\x0c\x63haracter_id\x18\x01 \x01(\x03\"3\n\x1f\x41llianceInvitationAnswerRequest\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\"(\n\x13\x41llianceKickRequest\x12\x11\n\tkicked_id\x18\x01 \x01(\x03\"\x8f\x01\n\x14\x41llianceInvitedEvent\x12\x16\n\x0erecruiter_name\x18\x01 \x01(\t\x12_\n\x14\x61lliance_information\x18\x02 \x01(\x0b\x32\x41.com.ankama.dofus.server.game.protocol.common.AllianceInformation\"\xa3\x01\n%AllianceInvitationStateRecruiterEvent\x12\x16\n\x0erecruited_name\x18\x01 \x01(\t\x12\x62\n\x10invitation_state\x18\x02 \x01(\x0e\x32H.com.ankama.dofus.server.game.protocol.common.SocialGroupInvitationState\"\x8b\x01\n%AllianceInvitationStateRecruitedEvent\x12\x62\n\x10invitation_state\x18\x01 \x01(\x0e\x32H.com.ankama.dofus.server.game.protocol.common.SocialGroupInvitationState\"\x8b\x01\n\x17\x41llianceMembershipEvent\x12_\n\x14\x61lliance_information\x18\x01 \x01(\x0b\x32\x41.com.ankama.dofus.server.game.protocol.common.AllianceInformation\x12\x0f\n\x07rank_id\x18\x02 \x01(\x05\"\x87\x01\n\x13\x41llianceJoinedEvent\x12_\n\x14\x61lliance_information\x18\x01 \x01(\x0b\x32\x41.com.ankama.dofus.server.game.protocol.common.AllianceInformation\x12\x0f\n\x07rank_id\x18\x02 \x01(\x05\"?\n\x1a\x41llianceMemberLeavingEvent\x12\x0e\n\x06kicked\x18\x01 \x01(\x08\x12\x11\n\tmember_id\x18\x02 \x01(\x03\"\x13\n\x11\x41llianceLeftEvent\"t\n\x19\x41llianceMemberUpdateEvent\x12W\n\x06member\x18\x01 \x01(\x0b\x32G.com.ankama.dofus.server.game.protocol.common.AllianceMemberInformationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alliance_member_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALLIANCEINVITATIONREQUEST']._serialized_start=94
  _globals['_ALLIANCEINVITATIONREQUEST']._serialized_end=143
  _globals['_ALLIANCEINVITATIONANSWERREQUEST']._serialized_start=145
  _globals['_ALLIANCEINVITATIONANSWERREQUEST']._serialized_end=196
  _globals['_ALLIANCEKICKREQUEST']._serialized_start=198
  _globals['_ALLIANCEKICKREQUEST']._serialized_end=238
  _globals['_ALLIANCEINVITEDEVENT']._serialized_start=241
  _globals['_ALLIANCEINVITEDEVENT']._serialized_end=384
  _globals['_ALLIANCEINVITATIONSTATERECRUITEREVENT']._serialized_start=387
  _globals['_ALLIANCEINVITATIONSTATERECRUITEREVENT']._serialized_end=550
  _globals['_ALLIANCEINVITATIONSTATERECRUITEDEVENT']._serialized_start=553
  _globals['_ALLIANCEINVITATIONSTATERECRUITEDEVENT']._serialized_end=692
  _globals['_ALLIANCEMEMBERSHIPEVENT']._serialized_start=695
  _globals['_ALLIANCEMEMBERSHIPEVENT']._serialized_end=834
  _globals['_ALLIANCEJOINEDEVENT']._serialized_start=837
  _globals['_ALLIANCEJOINEDEVENT']._serialized_end=972
  _globals['_ALLIANCEMEMBERLEAVINGEVENT']._serialized_start=974
  _globals['_ALLIANCEMEMBERLEAVINGEVENT']._serialized_end=1037
  _globals['_ALLIANCELEFTEVENT']._serialized_start=1039
  _globals['_ALLIANCELEFTEVENT']._serialized_end=1058
  _globals['_ALLIANCEMEMBERUPDATEEVENT']._serialized_start=1060
  _globals['_ALLIANCEMEMBERUPDATEEVENT']._serialized_end=1176
# @@protoc_insertion_point(module_scope)
