# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alliance_rank.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'alliance_rank.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61lliance_rank.proto\x12\x33\x63om.ankama.dofus.server.game.protocol.alliance.rank\x1a\x0c\x63ommon.proto\"S\n\x1b\x41llianceRankCreationRequest\x12\x16\n\x0eparent_rank_id\x18\x01 \x01(\x05\x12\x0e\n\x06gfx_id\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\"l\n\x1c\x41llianceRankUpdateAllRequest\x12L\n\x05ranks\x18\x01 \x03(\x0b\x32=.com.ankama.dofus.server.game.protocol.common.RankInformation\"K\n\x1b\x41llianceRankDeletionRequest\x12\x0f\n\x07rank_id\x18\x01 \x01(\x05\x12\x1b\n\x13replacement_rank_id\x18\x02 \x01(\x05\"h\n\x19\x41llianceRankUpdateRequest\x12K\n\x04rank\x18\x01 \x01(\x0b\x32=.com.ankama.dofus.server.game.protocol.common.RankInformation\"\x16\n\x14\x41llianceRanksRequest\"?\n\x19\x41llianceRankChangeRequest\x12\x11\n\tmember_id\x18\x01 \x01(\x03\x12\x0f\n\x07rank_id\x18\x02 \x01(\x05\"b\n\x12\x41llianceRanksEvent\x12L\n\x05ranks\x18\x01 \x03(\x0b\x32=.com.ankama.dofus.server.game.protocol.common.RankInformation\">\n\x1b\x41llianceRightsUpdateRequest\x12\x0f\n\x07rank_id\x18\x01 \x01(\x05\x12\x0e\n\x06rights\x18\x02 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alliance_rank_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALLIANCERANKCREATIONREQUEST']._serialized_start=90
  _globals['_ALLIANCERANKCREATIONREQUEST']._serialized_end=173
  _globals['_ALLIANCERANKUPDATEALLREQUEST']._serialized_start=175
  _globals['_ALLIANCERANKUPDATEALLREQUEST']._serialized_end=283
  _globals['_ALLIANCERANKDELETIONREQUEST']._serialized_start=285
  _globals['_ALLIANCERANKDELETIONREQUEST']._serialized_end=360
  _globals['_ALLIANCERANKUPDATEREQUEST']._serialized_start=362
  _globals['_ALLIANCERANKUPDATEREQUEST']._serialized_end=466
  _globals['_ALLIANCERANKSREQUEST']._serialized_start=468
  _globals['_ALLIANCERANKSREQUEST']._serialized_end=490
  _globals['_ALLIANCERANKCHANGEREQUEST']._serialized_start=492
  _globals['_ALLIANCERANKCHANGEREQUEST']._serialized_end=555
  _globals['_ALLIANCERANKSEVENT']._serialized_start=557
  _globals['_ALLIANCERANKSEVENT']._serialized_end=655
  _globals['_ALLIANCERIGHTSUPDATEREQUEST']._serialized_start=657
  _globals['_ALLIANCERIGHTSUPDATEREQUEST']._serialized_end=719
# @@protoc_insertion_point(module_scope)
