# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alteration.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'alteration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61lteration.proto\x12\x30\x63om.ankama.dofus.server.game.protocol.alteration\x1a\x0c\x63ommon.proto\"e\n\x10\x41lterationsEvent\x12Q\n\x0b\x61lterations\x18\x01 \x03(\x0b\x32<.com.ankama.dofus.server.game.protocol.alteration.Alteration\"h\n\x14\x41lterationAddedEvent\x12P\n\nalteration\x18\x01 \x01(\x0b\x32<.com.ankama.dofus.server.game.protocol.alteration.Alteration\"j\n\x16\x41lterationRemovedEvent\x12P\n\nalteration\x18\x01 \x01(\x0b\x32<.com.ankama.dofus.server.game.protocol.alteration.Alteration\"k\n\x16\x41lterationsUpdateEvent\x12Q\n\x0b\x61lterations\x18\x01 \x03(\x0b\x32<.com.ankama.dofus.server.game.protocol.alteration.Alteration\"\x90\x03\n\nAlteration\x12\x15\n\ralteration_id\x18\x01 \x01(\x03\x12\x15\n\rcreation_time\x18\x02 \x01(\x03\x12n\n\x0f\x65xpiration_type\x18\x03 \x01(\x0e\x32U.com.ankama.dofus.server.game.protocol.alteration.Alteration.AlterationExpirationType\x12\x18\n\x10\x65xpiration_value\x18\x04 \x01(\x03\x12K\n\x07\x65\x66\x66\x65\x63ts\x18\x05 \x03(\x0b\x32:.com.ankama.dofus.server.game.protocol.common.ObjectEffect\"}\n\x18\x41lterationExpirationType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08INFINITE\x10\x01\x12\x08\n\x04\x44\x41TE\x10\x02\x12\x0f\n\x0b\x46IGHT_COUNT\x10\x03\x12\x14\n\x10\x46IGHTS_WON_COUNT\x10\x04\x12\x15\n\x11\x46IGHTS_LOST_COUNT\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alteration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALTERATIONSEVENT']._serialized_start=84
  _globals['_ALTERATIONSEVENT']._serialized_end=185
  _globals['_ALTERATIONADDEDEVENT']._serialized_start=187
  _globals['_ALTERATIONADDEDEVENT']._serialized_end=291
  _globals['_ALTERATIONREMOVEDEVENT']._serialized_start=293
  _globals['_ALTERATIONREMOVEDEVENT']._serialized_end=399
  _globals['_ALTERATIONSUPDATEEVENT']._serialized_start=401
  _globals['_ALTERATIONSUPDATEEVENT']._serialized_end=508
  _globals['_ALTERATION']._serialized_start=511
  _globals['_ALTERATION']._serialized_end=911
  _globals['_ALTERATION_ALTERATIONEXPIRATIONTYPE']._serialized_start=786
  _globals['_ALTERATION_ALTERATIONEXPIRATIONTYPE']._serialized_end=911
# @@protoc_insertion_point(module_scope)
