# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: anomaly.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'anomaly.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ranomaly.proto\x12-com.ankama.dofus.server.game.protocol.anomaly\"\"\n AnomalySubareaInformationRequest\"\x94\x02\n\x1e\x41nomalySubareaInformationEvent\x12y\n\x08subareas\x18\x01 \x03(\x0b\x32g.com.ankama.dofus.server.game.protocol.anomaly.AnomalySubareaInformationEvent.AnomalySubareaInformation\x1aw\n\x19\x41nomalySubareaInformation\x12\x12\n\nsubarea_id\x18\x01 \x01(\x05\x12\x13\n\x0breward_rate\x18\x02 \x01(\x05\x12\x13\n\x0bhas_anomaly\x18\x03 \x01(\x08\x12\x1c\n\x14\x61nomaly_closing_time\x18\x04 \x01(\x03\"K\n\x11\x41nomalyStateEvent\x12\x12\n\nsubarea_id\x18\x01 \x01(\x05\x12\x0c\n\x04open\x18\x02 \x01(\x08\x12\x14\n\x0c\x63losing_time\x18\x03 \x01(\x03\"(\n\x12\x41nomalyOpenedEvent\x12\x12\n\nsubarea_id\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anomaly_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANOMALYSUBAREAINFORMATIONREQUEST']._serialized_start=64
  _globals['_ANOMALYSUBAREAINFORMATIONREQUEST']._serialized_end=98
  _globals['_ANOMALYSUBAREAINFORMATIONEVENT']._serialized_start=101
  _globals['_ANOMALYSUBAREAINFORMATIONEVENT']._serialized_end=377
  _globals['_ANOMALYSUBAREAINFORMATIONEVENT_ANOMALYSUBAREAINFORMATION']._serialized_start=258
  _globals['_ANOMALYSUBAREAINFORMATIONEVENT_ANOMALYSUBAREAINFORMATION']._serialized_end=377
  _globals['_ANOMALYSTATEEVENT']._serialized_start=379
  _globals['_ANOMALYSTATEEVENT']._serialized_end=454
  _globals['_ANOMALYOPENEDEVENT']._serialized_start=456
  _globals['_ANOMALYOPENEDEVENT']._serialized_end=496
# @@protoc_insertion_point(module_scope)
