# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: choice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'choice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63hoice.proto\x12,com.ankama.dofus.server.game.protocol.choice\"&\n\x06\x43hoice\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08position\x18\x02 \x01(\x05\"<\n\x0bVotedChoice\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08position\x18\x02 \x01(\x05\x12\x0f\n\x07players\x18\x03 \x03(\x03\"s\n\x14\x43hoiceSelectionEvent\x12\x14\n\x0cselection_id\x18\x01 \x01(\x05\x12\x45\n\x07\x63hoices\x18\x02 \x03(\x0b\x32\x34.com.ankama.dofus.server.game.protocol.choice.Choice\"\x94\x01\n\x19\x46ightChoiceSelectionEvent\x12\x14\n\x0cselection_id\x18\x01 \x01(\x05\x12\x1a\n\x12target_protocol_id\x18\x02 \x01(\x03\x12\x45\n\x07\x63hoices\x18\x03 \x03(\x0b\x32\x34.com.ankama.dofus.server.game.protocol.choice.Choice\"\'\n\x13\x43hoiceSelectedEvent\x12\x10\n\x08position\x18\x01 \x01(\x05\")\n\x15\x43hoiceSelectedRequest\x12\x10\n\x08position\x18\x01 \x01(\x05\"\x85\x01\n!CurrentGlobalChoiceSelectionEvent\x12\x14\n\x0cselection_id\x18\x01 \x01(\x05\x12J\n\x07\x63hoices\x18\x02 \x03(\x0b\x32\x39.com.ankama.dofus.server.game.protocol.choice.VotedChoice\"y\n\x1aGlobalChoiceSelectionEvent\x12\x14\n\x0cselection_id\x18\x01 \x01(\x05\x12\x45\n\x07\x63hoices\x18\x02 \x03(\x0b\x32\x34.com.ankama.dofus.server.game.protocol.choice.Choice\"/\n\x1bGlobalChoiceSelectedRequest\x12\x10\n\x08position\x18\x01 \x01(\x05\"C\n\x15GlobalChoiceVoteEvent\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\x12\x17\n\x0f\x63hoice_position\x18\x02 \x01(\x05\"-\n\x19GlobalChoiceSelectedEvent\x12\x10\n\x08position\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'choice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHOICE']._serialized_start=62
  _globals['_CHOICE']._serialized_end=100
  _globals['_VOTEDCHOICE']._serialized_start=102
  _globals['_VOTEDCHOICE']._serialized_end=162
  _globals['_CHOICESELECTIONEVENT']._serialized_start=164
  _globals['_CHOICESELECTIONEVENT']._serialized_end=279
  _globals['_FIGHTCHOICESELECTIONEVENT']._serialized_start=282
  _globals['_FIGHTCHOICESELECTIONEVENT']._serialized_end=430
  _globals['_CHOICESELECTEDEVENT']._serialized_start=432
  _globals['_CHOICESELECTEDEVENT']._serialized_end=471
  _globals['_CHOICESELECTEDREQUEST']._serialized_start=473
  _globals['_CHOICESELECTEDREQUEST']._serialized_end=514
  _globals['_CURRENTGLOBALCHOICESELECTIONEVENT']._serialized_start=517
  _globals['_CURRENTGLOBALCHOICESELECTIONEVENT']._serialized_end=650
  _globals['_GLOBALCHOICESELECTIONEVENT']._serialized_start=652
  _globals['_GLOBALCHOICESELECTIONEVENT']._serialized_end=773
  _globals['_GLOBALCHOICESELECTEDREQUEST']._serialized_start=775
  _globals['_GLOBALCHOICESELECTEDREQUEST']._serialized_end=822
  _globals['_GLOBALCHOICEVOTEEVENT']._serialized_start=824
  _globals['_GLOBALCHOICEVOTEEVENT']._serialized_end=891
  _globals['_GLOBALCHOICESELECTEDEVENT']._serialized_start=893
  _globals['_GLOBALCHOICESELECTEDEVENT']._serialized_end=938
# @@protoc_insertion_point(module_scope)
