# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: connection.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'connection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63onnection.proto\x12\x30\x63om.ankama.dofus.server.game.protocol.connection\"B\n\x15IdentificationRequest\x12\x12\n\nticket_key\x18\x01 \x01(\t\x12\x15\n\rlanguage_code\x18\x02 \x01(\t\"\x10\n\x0eReloginRequest\"\x1c\n\x0bPingRequest\x12\r\n\x05quiet\x18\x01 \x01(\x08\"\x1a\n\tPongEvent\x12\r\n\x05quiet\x18\x01 \x01(\x08\"#\n!AuthenticationTicketAcceptedEvent\"\x17\n\x15\x41lreadyConnectedEvent\"S\n\x1aReconnectToGameServerEvent\x12\x13\n\x0bvalid_token\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\x12\x11\n\tserver_id\x18\x03 \x01(\x05\")\n\x15OptionalFeaturesEvent\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x05\"7\n\x11ReloginTokenEvent\x12\x13\n\x0bvalid_token\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\"3\n\x10QueueStatusEvent\x12\x10\n\x08position\x18\x01 \x01(\x05\x12\r\n\x05total\x18\x02 \x01(\x05\"\"\n AuthenticationTicketRefusedEventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IDENTIFICATIONREQUEST']._serialized_start=70
  _globals['_IDENTIFICATIONREQUEST']._serialized_end=136
  _globals['_RELOGINREQUEST']._serialized_start=138
  _globals['_RELOGINREQUEST']._serialized_end=154
  _globals['_PINGREQUEST']._serialized_start=156
  _globals['_PINGREQUEST']._serialized_end=184
  _globals['_PONGEVENT']._serialized_start=186
  _globals['_PONGEVENT']._serialized_end=212
  _globals['_AUTHENTICATIONTICKETACCEPTEDEVENT']._serialized_start=214
  _globals['_AUTHENTICATIONTICKETACCEPTEDEVENT']._serialized_end=249
  _globals['_ALREADYCONNECTEDEVENT']._serialized_start=251
  _globals['_ALREADYCONNECTEDEVENT']._serialized_end=274
  _globals['_RECONNECTTOGAMESERVEREVENT']._serialized_start=276
  _globals['_RECONNECTTOGAMESERVEREVENT']._serialized_end=359
  _globals['_OPTIONALFEATURESEVENT']._serialized_start=361
  _globals['_OPTIONALFEATURESEVENT']._serialized_end=402
  _globals['_RELOGINTOKENEVENT']._serialized_start=404
  _globals['_RELOGINTOKENEVENT']._serialized_end=459
  _globals['_QUEUESTATUSEVENT']._serialized_start=461
  _globals['_QUEUESTATUSEVENT']._serialized_end=512
  _globals['_AUTHENTICATIONTICKETREFUSEDEVENT']._serialized_start=514
  _globals['_AUTHENTICATIONTICKETREFUSEDEVENT']._serialized_end=548
# @@protoc_insertion_point(module_scope)
