# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: interactive_element.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'interactive_element.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19interactive_element.proto\x12\x39\x63om.ankama.dofus.server.game.protocol.interactive.element\x1a\x0c\x63ommon.proto\"\x83\x01\n\x15InteractiveUseRequest\x12\x12\n\nelement_id\x18\x01 \x01(\x05\x12\x1a\n\x12skill_instance_uid\x18\x02 \x01(\x05\x12!\n\x14specific_instance_id\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\x17\n\x15_specific_instance_id\"J\n\x18InteractiveUseErrorEvent\x12\x12\n\nelement_id\x18\x01 \x01(\x05\x12\x1a\n\x12skill_instance_uid\x18\x02 \x01(\x05\"s\n\x14InteractiveUsedEvent\x12\x11\n\tentity_id\x18\x01 \x01(\x03\x12\x12\n\nelement_id\x18\x02 \x01(\x05\x12\x10\n\x08skill_id\x18\x03 \x01(\x05\x12\x10\n\x08\x64uration\x18\x04 \x01(\x05\x12\x10\n\x08\x63\x61n_move\x18\x05 \x01(\x08\"@\n\x18InteractiveUseEndedEvent\x12\x12\n\nelement_id\x18\x01 \x01(\x05\x12\x10\n\x08skill_id\x18\x02 \x01(\x05\"{\n\x19InteractiveMapUpdateEvent\x12^\n\x14interactive_elements\x18\x01 \x03(\x0b\x32@.com.ankama.dofus.server.game.protocol.common.InteractiveElement\"l\n\x14StatedMapUpdateEvent\x12T\n\x0fstated_elements\x18\x01 \x03(\x0b\x32;.com.ankama.dofus.server.game.protocol.common.StatedElement\"\x7f\n\x1eInteractiveElementUpdatedEvent\x12]\n\x13interactive_element\x18\x01 \x01(\x0b\x32@.com.ankama.dofus.server.game.protocol.common.InteractiveElement\"p\n\x19StatedElementUpdatedEvent\x12S\n\x0estated_element\x18\x01 \x01(\x0b\x32;.com.ankama.dofus.server.game.protocol.common.StatedElementb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interactive_element_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTERACTIVEUSEREQUEST']._serialized_start=103
  _globals['_INTERACTIVEUSEREQUEST']._serialized_end=234
  _globals['_INTERACTIVEUSEERROREVENT']._serialized_start=236
  _globals['_INTERACTIVEUSEERROREVENT']._serialized_end=310
  _globals['_INTERACTIVEUSEDEVENT']._serialized_start=312
  _globals['_INTERACTIVEUSEDEVENT']._serialized_end=427
  _globals['_INTERACTIVEUSEENDEDEVENT']._serialized_start=429
  _globals['_INTERACTIVEUSEENDEDEVENT']._serialized_end=493
  _globals['_INTERACTIVEMAPUPDATEEVENT']._serialized_start=495
  _globals['_INTERACTIVEMAPUPDATEEVENT']._serialized_end=618
  _globals['_STATEDMAPUPDATEEVENT']._serialized_start=620
  _globals['_STATEDMAPUPDATEEVENT']._serialized_end=728
  _globals['_INTERACTIVEELEMENTUPDATEDEVENT']._serialized_start=730
  _globals['_INTERACTIVEELEMENTUPDATEDEVENT']._serialized_end=857
  _globals['_STATEDELEMENTUPDATEDEVENT']._serialized_start=859
  _globals['_STATEDELEMENTUPDATEDEVENT']._serialized_end=971
# @@protoc_insertion_point(module_scope)
