# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: living_object.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'living_object.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13living_object.proto\x12\x33\x63om.ankama.dofus.server.game.protocol.living.object\"D\n\x1aLivingObjectMessageRequest\x12\x12\n\nmessage_id\x18\x01 \x01(\x05\x12\x12\n\nobject_gid\x18\x02 \x01(\x05\"E\n\x1dLivingObjectDissociateRequest\x12\x12\n\nobject_uid\x18\x01 \x01(\x05\x12\x10\n\x08position\x18\x02 \x01(\x05\"V\n\x1dLivingObjectChangeSkinRequest\x12\x12\n\nobject_uid\x18\x01 \x01(\x05\x12\x10\n\x08position\x18\x02 \x01(\x05\x12\x0f\n\x07skin_id\x18\x03 \x01(\x05\"i\n\x18LivingObjectMessageEvent\x12\x12\n\nmessage_id\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x12\n\nowner_name\x18\x03 \x01(\t\x12\x12\n\nobject_gid\x18\x04 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'living_object_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIVINGOBJECTMESSAGEREQUEST']._serialized_start=76
  _globals['_LIVINGOBJECTMESSAGEREQUEST']._serialized_end=144
  _globals['_LIVINGOBJECTDISSOCIATEREQUEST']._serialized_start=146
  _globals['_LIVINGOBJECTDISSOCIATEREQUEST']._serialized_end=215
  _globals['_LIVINGOBJECTCHANGESKINREQUEST']._serialized_start=217
  _globals['_LIVINGOBJECTCHANGESKINREQUEST']._serialized_end=303
  _globals['_LIVINGOBJECTMESSAGEEVENT']._serialized_start=305
  _globals['_LIVINGOBJECTMESSAGEEVENT']._serialized_end=410
# @@protoc_insertion_point(module_scope)
