# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shop.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'shop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nshop.proto\x12*com.ankama.dofus.server.game.protocol.shop\x1a\x0c\x63ommon.proto\"K\n\x17\x41\x63\x63\x65ssoryPreviewRequest\x12\x12\n\nobject_gid\x18\x01 \x03(\x05\x12\x1c\n\x14show_current_objects\x18\x02 \x01(\x08\"\xca\x01\n\x1a\x41\x63\x63\x65ssoryPreviewErrorEvent\x12k\n\x05\x65rror\x18\x01 \x01(\x0e\x32\\.com.ankama.dofus.server.game.protocol.shop.AccessoryPreviewErrorEvent.AccessoryPreviewError\"?\n\x15\x41\x63\x63\x65ssoryPreviewError\x12\t\n\x05\x45RROR\x10\x00\x12\r\n\tCOOL_DOWN\x10\x01\x12\x0c\n\x08\x42\x41\x44_ITEM\x10\x02\"_\n\x15\x41\x63\x63\x65ssoryPreviewEvent\x12\x46\n\x04look\x18\x01 \x01(\x0b\x32\x38.com.ankama.dofus.server.game.protocol.common.EntityLookb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCESSORYPREVIEWREQUEST']._serialized_start=72
  _globals['_ACCESSORYPREVIEWREQUEST']._serialized_end=147
  _globals['_ACCESSORYPREVIEWERROREVENT']._serialized_start=150
  _globals['_ACCESSORYPREVIEWERROREVENT']._serialized_end=352
  _globals['_ACCESSORYPREVIEWERROREVENT_ACCESSORYPREVIEWERROR']._serialized_start=289
  _globals['_ACCESSORYPREVIEWERROREVENT_ACCESSORYPREVIEWERROR']._serialized_end=352
  _globals['_ACCESSORYPREVIEWEVENT']._serialized_start=354
  _globals['_ACCESSORYPREVIEWEVENT']._serialized_end=449
# @@protoc_insertion_point(module_scope)
