# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tag_storage.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'tag_storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11tag_storage.proto\x12\x31\x63om.ankama.dofus.server.game.protocol.tag.storage\"3\n\x14\x41\x64\x64TagStorageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05picto\x18\x02 \x01(\x05\"1\n\x15\x41\x64\x64TagStorageResponse\x12\x18\n\x10tag_storage_uuid\x18\x01 \x01(\t\"3\n\x17RemoveTagStorageRequest\x12\x18\n\x10tag_storage_uuid\x18\x01 \x01(\t\"4\n\x18RemoveTagStorageResponse\x12\x18\n\x10tag_storage_uuid\x18\x01 \x01(\t\"\x83\x01\n\x13\x41\x64\x64TagObjectRequest\x12l\n\x19tag_object_update_content\x18\x01 \x03(\x0b\x32I.com.ankama.dofus.server.game.protocol.tag.storage.TagObjectUpdateContent\"*\n\x14\x41\x64\x64TagObjectResponse\x12\x12\n\nobject_ids\x18\x01 \x03(\x05\"\x86\x01\n\x16RemoveTagObjectRequest\x12l\n\x19tag_object_update_content\x18\x01 \x03(\x0b\x32I.com.ankama.dofus.server.game.protocol.tag.storage.TagObjectUpdateContent\"-\n\x17RemoveTagObjectResponse\x12\x12\n\nobject_ids\x18\x01 \x03(\x05\"E\n\x16TagObjectUpdateContent\x12\x18\n\x10tag_storage_uuid\x18\x01 \x01(\t\x12\x11\n\tobject_id\x18\x02 \x01(\x05\"}\n\x1eUpdateTagStorageContentRequest\x12[\n\x10tag_storage_data\x18\x01 \x01(\x0b\x32\x41.com.ankama.dofus.server.game.protocol.tag.storage.TagStorageData\";\n\x1fUpdateTagStorageContentResponse\x12\x18\n\x10tag_storage_uuid\x18\x01 \x01(\t\"u\n\x17TagStoragesRefreshEvent\x12Z\n\x0ftag_information\x18\x01 \x03(\x0b\x32\x41.com.ankama.dofus.server.game.protocol.tag.storage.TagInformation\"\xc8\x01\n\x0eTagInformation\x12[\n\x10tag_storage_data\x18\x01 \x01(\x0b\x32\x41.com.ankama.dofus.server.game.protocol.tag.storage.TagStorageData\x12Y\n\x0ftag_object_data\x18\x02 \x01(\x0b\x32@.com.ankama.dofus.server.game.protocol.tag.storage.TagObjectData\"G\n\x0eTagStorageData\x12\x18\n\x10tag_storage_uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05picto\x18\x03 \x01(\x05\")\n\rTagObjectData\x12\x18\n\x10tag_object_uuids\x18\x01 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tag_storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDTAGSTORAGEREQUEST']._serialized_start=72
  _globals['_ADDTAGSTORAGEREQUEST']._serialized_end=123
  _globals['_ADDTAGSTORAGERESPONSE']._serialized_start=125
  _globals['_ADDTAGSTORAGERESPONSE']._serialized_end=174
  _globals['_REMOVETAGSTORAGEREQUEST']._serialized_start=176
  _globals['_REMOVETAGSTORAGEREQUEST']._serialized_end=227
  _globals['_REMOVETAGSTORAGERESPONSE']._serialized_start=229
  _globals['_REMOVETAGSTORAGERESPONSE']._serialized_end=281
  _globals['_ADDTAGOBJECTREQUEST']._serialized_start=284
  _globals['_ADDTAGOBJECTREQUEST']._serialized_end=415
  _globals['_ADDTAGOBJECTRESPONSE']._serialized_start=417
  _globals['_ADDTAGOBJECTRESPONSE']._serialized_end=459
  _globals['_REMOVETAGOBJECTREQUEST']._serialized_start=462
  _globals['_REMOVETAGOBJECTREQUEST']._serialized_end=596
  _globals['_REMOVETAGOBJECTRESPONSE']._serialized_start=598
  _globals['_REMOVETAGOBJECTRESPONSE']._serialized_end=643
  _globals['_TAGOBJECTUPDATECONTENT']._serialized_start=645
  _globals['_TAGOBJECTUPDATECONTENT']._serialized_end=714
  _globals['_UPDATETAGSTORAGECONTENTREQUEST']._serialized_start=716
  _globals['_UPDATETAGSTORAGECONTENTREQUEST']._serialized_end=841
  _globals['_UPDATETAGSTORAGECONTENTRESPONSE']._serialized_start=843
  _globals['_UPDATETAGSTORAGECONTENTRESPONSE']._serialized_end=902
  _globals['_TAGSTORAGESREFRESHEVENT']._serialized_start=904
  _globals['_TAGSTORAGESREFRESHEVENT']._serialized_end=1021
  _globals['_TAGINFORMATION']._serialized_start=1024
  _globals['_TAGINFORMATION']._serialized_end=1224
  _globals['_TAGSTORAGEDATA']._serialized_start=1226
  _globals['_TAGSTORAGEDATA']._serialized_end=1297
  _globals['_TAGOBJECTDATA']._serialized_start=1299
  _globals['_TAGOBJECTDATA']._serialized_end=1340
# @@protoc_insertion_point(module_scope)
