# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/ankama/dofus/server/game/protocol/alliance/member.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'com/ankama/dofus/server/game/protocol/alliance/member.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.ankama.dofus.server.game.protocol import common_pb2 as com_dot_ankama_dot_dofus_dot_server_dot_game_dot_protocol_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;com/ankama/dofus/server/game/protocol/alliance/member.proto\x12\x35\x63om.ankama.dofus.server.game.protocol.alliance.member\x1a\x32\x63om/ankama/dofus/server/game/protocol/common.proto\"1\n\x19\x41llianceInvitationRequest\x12\x14\n\x0c\x63haracter_id\x18\x01 \x01(\x03\"3\n\x1f\x41llianceInvitationAnswerRequest\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\"(\n\x13\x41llianceKickRequest\x12\x11\n\tkicked_id\x18\x01 \x01(\x03\"\x8f\x01\n\x14\x41llianceInvitedEvent\x12\x16\n\x0erecruiter_name\x18\x01 \x01(\t\x12_\n\x14\x61lliance_information\x18\x02 \x01(\x0b\x32\x41.com.ankama.dofus.server.game.protocol.common.AllianceInformation\"\xa3\x01\n%AllianceInvitationStateRecruiterEvent\x12\x16\n\x0erecruited_name\x18\x01 \x01(\t\x12\x62\n\x10invitation_state\x18\x02 \x01(\x0e\x32H.com.ankama.dofus.server.game.protocol.common.SocialGroupInvitationState\"\x8b\x01\n%AllianceInvitationStateRecruitedEvent\x12\x62\n\x10invitation_state\x18\x01 \x01(\x0e\x32H.com.ankama.dofus.server.game.protocol.common.SocialGroupInvitationState\"\x8b\x01\n\x17\x41llianceMembershipEvent\x12_\n\x14\x61lliance_information\x18\x01 \x01(\x0b\x32\x41.com.ankama.dofus.server.game.protocol.common.AllianceInformation\x12\x0f\n\x07rank_id\x18\x02 \x01(\x05\"\x87\x01\n\x13\x41llianceJoinedEvent\x12_\n\x14\x61lliance_information\x18\x01 \x01(\x0b\x32\x41.com.ankama.dofus.server.game.protocol.common.AllianceInformation\x12\x0f\n\x07rank_id\x18\x02 \x01(\x05\"?\n\x1a\x41llianceMemberLeavingEvent\x12\x0e\n\x06kicked\x18\x01 \x01(\x08\x12\x11\n\tmember_id\x18\x02 \x01(\x03\"\x13\n\x11\x41llianceLeftEvent\"t\n\x19\x41llianceMemberUpdateEvent\x12W\n\x06member\x18\x01 \x01(\x0b\x32G.com.ankama.dofus.server.game.protocol.common.AllianceMemberInformationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.ankama.dofus.server.game.protocol.alliance.member_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALLIANCEINVITATIONREQUEST']._serialized_start=170
  _globals['_ALLIANCEINVITATIONREQUEST']._serialized_end=219
  _globals['_ALLIANCEINVITATIONANSWERREQUEST']._serialized_start=221
  _globals['_ALLIANCEINVITATIONANSWERREQUEST']._serialized_end=272
  _globals['_ALLIANCEKICKREQUEST']._serialized_start=274
  _globals['_ALLIANCEKICKREQUEST']._serialized_end=314
  _globals['_ALLIANCEINVITEDEVENT']._serialized_start=317
  _globals['_ALLIANCEINVITEDEVENT']._serialized_end=460
  _globals['_ALLIANCEINVITATIONSTATERECRUITEREVENT']._serialized_start=463
  _globals['_ALLIANCEINVITATIONSTATERECRUITEREVENT']._serialized_end=626
  _globals['_ALLIANCEINVITATIONSTATERECRUITEDEVENT']._serialized_start=629
  _globals['_ALLIANCEINVITATIONSTATERECRUITEDEVENT']._serialized_end=768
  _globals['_ALLIANCEMEMBERSHIPEVENT']._serialized_start=771
  _globals['_ALLIANCEMEMBERSHIPEVENT']._serialized_end=910
  _globals['_ALLIANCEJOINEDEVENT']._serialized_start=913
  _globals['_ALLIANCEJOINEDEVENT']._serialized_end=1048
  _globals['_ALLIANCEMEMBERLEAVINGEVENT']._serialized_start=1050
  _globals['_ALLIANCEMEMBERLEAVINGEVENT']._serialized_end=1113
  _globals['_ALLIANCELEFTEVENT']._serialized_start=1115
  _globals['_ALLIANCELEFTEVENT']._serialized_end=1134
  _globals['_ALLIANCEMEMBERUPDATEEVENT']._serialized_start=1136
  _globals['_ALLIANCEMEMBERUPDATEEVENT']._serialized_end=1252
# @@protoc_insertion_point(module_scope)
