# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/ankama/dofus/server/game/protocol/alliance/rank.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'com/ankama/dofus/server/game/protocol/alliance/rank.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.ankama.dofus.server.game.protocol import common_pb2 as com_dot_ankama_dot_dofus_dot_server_dot_game_dot_protocol_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9com/ankama/dofus/server/game/protocol/alliance/rank.proto\x12\x33\x63om.ankama.dofus.server.game.protocol.alliance.rank\x1a\x32\x63om/ankama/dofus/server/game/protocol/common.proto\"S\n\x1b\x41llianceRankCreationRequest\x12\x16\n\x0eparent_rank_id\x18\x01 \x01(\x05\x12\x0e\n\x06gfx_id\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\"l\n\x1c\x41llianceRankUpdateAllRequest\x12L\n\x05ranks\x18\x01 \x03(\x0b\x32=.com.ankama.dofus.server.game.protocol.common.RankInformation\"K\n\x1b\x41llianceRankDeletionRequest\x12\x0f\n\x07rank_id\x18\x01 \x01(\x05\x12\x1b\n\x13replacement_rank_id\x18\x02 \x01(\x05\"h\n\x19\x41llianceRankUpdateRequest\x12K\n\x04rank\x18\x01 \x01(\x0b\x32=.com.ankama.dofus.server.game.protocol.common.RankInformation\"\x16\n\x14\x41llianceRanksRequest\"?\n\x19\x41llianceRankChangeRequest\x12\x11\n\tmember_id\x18\x01 \x01(\x03\x12\x0f\n\x07rank_id\x18\x02 \x01(\x05\"b\n\x12\x41llianceRanksEvent\x12L\n\x05ranks\x18\x01 \x03(\x0b\x32=.com.ankama.dofus.server.game.protocol.common.RankInformation\">\n\x1b\x41llianceRightsUpdateRequest\x12\x0f\n\x07rank_id\x18\x01 \x01(\x05\x12\x0e\n\x06rights\x18\x02 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.ankama.dofus.server.game.protocol.alliance.rank_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALLIANCERANKCREATIONREQUEST']._serialized_start=166
  _globals['_ALLIANCERANKCREATIONREQUEST']._serialized_end=249
  _globals['_ALLIANCERANKUPDATEALLREQUEST']._serialized_start=251
  _globals['_ALLIANCERANKUPDATEALLREQUEST']._serialized_end=359
  _globals['_ALLIANCERANKDELETIONREQUEST']._serialized_start=361
  _globals['_ALLIANCERANKDELETIONREQUEST']._serialized_end=436
  _globals['_ALLIANCERANKUPDATEREQUEST']._serialized_start=438
  _globals['_ALLIANCERANKUPDATEREQUEST']._serialized_end=542
  _globals['_ALLIANCERANKSREQUEST']._serialized_start=544
  _globals['_ALLIANCERANKSREQUEST']._serialized_end=566
  _globals['_ALLIANCERANKCHANGEREQUEST']._serialized_start=568
  _globals['_ALLIANCERANKCHANGEREQUEST']._serialized_end=631
  _globals['_ALLIANCERANKSEVENT']._serialized_start=633
  _globals['_ALLIANCERANKSEVENT']._serialized_end=731
  _globals['_ALLIANCERIGHTSUPDATEREQUEST']._serialized_start=733
  _globals['_ALLIANCERIGHTSUPDATEREQUEST']._serialized_end=795
# @@protoc_insertion_point(module_scope)
