# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: appearance.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'appearance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ppearance.proto\x12.com.ankama.dofus.server.game.protocol.cosmetic\"\x1d\n\x1b\x43haracterAppearancesRequest\"\xd2\x01\n\x1c\x43haracterAppearancesResponse\x12W\n\x0f\x63haracter_faces\x18\x01 \x01(\x0b\x32>.com.ankama.dofus.server.game.protocol.cosmetic.CharacterFaces\x12Y\n\x10\x63haracter_colors\x18\x02 \x01(\x0b\x32?.com.ankama.dofus.server.game.protocol.cosmetic.CharacterColors\"\xd8\x01\n\"CharacterAppearanceCollectionEvent\x12W\n\x0f\x63haracter_faces\x18\x01 \x01(\x0b\x32>.com.ankama.dofus.server.game.protocol.cosmetic.CharacterFaces\x12Y\n\x10\x63haracter_colors\x18\x02 \x01(\x0b\x32?.com.ankama.dofus.server.game.protocol.cosmetic.CharacterColors\"A\n\x0e\x43haracterFaces\x12\r\n\x05slots\x18\x01 \x01(\x05\x12\r\n\x05\x66\x61\x63\x65s\x18\x02 \x03(\x05\x12\x11\n\tmax_slots\x18\x03 \x01(\x05\"\x89\x01\n\x0f\x43haracterColors\x12\r\n\x05slots\x18\x01 \x01(\x05\x12T\n\x0e\x63olor_palettes\x18\x02 \x03(\x0b\x32<.com.ankama.dofus.server.game.protocol.cosmetic.ColorPalette\x12\x11\n\tmax_slots\x18\x03 \x01(\x05\"\x1e\n\x0c\x43olorPalette\x12\x0e\n\x06\x63olors\x18\x01 \x03(\x05\";\n\x1a\x43haracterUpdateFaceRequest\x12\x0f\n\x07\x66\x61\x63\x65_id\x18\x01 \x01(\x05\x12\x0c\n\x04slot\x18\x02 \x01(\x05\":\n\x19\x43haracterFaceUpdatedEvent\x12\x0f\n\x07\x66\x61\x63\x65_id\x18\x01 \x01(\x05\x12\x0c\n\x04slot\x18\x02 \x01(\x05\"<\n\x1c\x43haracterUpdateColorsRequest\x12\x0e\n\x06\x63olors\x18\x01 \x03(\x05\x12\x0c\n\x04slot\x18\x02 \x01(\x05\";\n\x1b\x43haracterColorsUpdatedEvent\x12\x0e\n\x06\x63olors\x18\x01 \x03(\x05\x12\x0c\n\x04slot\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'appearance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHARACTERAPPEARANCESREQUEST']._serialized_start=68
  _globals['_CHARACTERAPPEARANCESREQUEST']._serialized_end=97
  _globals['_CHARACTERAPPEARANCESRESPONSE']._serialized_start=100
  _globals['_CHARACTERAPPEARANCESRESPONSE']._serialized_end=310
  _globals['_CHARACTERAPPEARANCECOLLECTIONEVENT']._serialized_start=313
  _globals['_CHARACTERAPPEARANCECOLLECTIONEVENT']._serialized_end=529
  _globals['_CHARACTERFACES']._serialized_start=531
  _globals['_CHARACTERFACES']._serialized_end=596
  _globals['_CHARACTERCOLORS']._serialized_start=599
  _globals['_CHARACTERCOLORS']._serialized_end=736
  _globals['_COLORPALETTE']._serialized_start=738
  _globals['_COLORPALETTE']._serialized_end=768
  _globals['_CHARACTERUPDATEFACEREQUEST']._serialized_start=770
  _globals['_CHARACTERUPDATEFACEREQUEST']._serialized_end=829
  _globals['_CHARACTERFACEUPDATEDEVENT']._serialized_start=831
  _globals['_CHARACTERFACEUPDATEDEVENT']._serialized_end=889
  _globals['_CHARACTERUPDATECOLORSREQUEST']._serialized_start=891
  _globals['_CHARACTERUPDATECOLORSREQUEST']._serialized_end=951
  _globals['_CHARACTERCOLORSUPDATEDEVENT']._serialized_start=953
  _globals['_CHARACTERCOLORSUPDATEDEVENT']._serialized_end=1012
# @@protoc_insertion_point(module_scope)
