# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: guild_member.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'guild_member.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12guild_member.proto\x12\x32\x63om.ankama.dofus.server.game.protocol.guild.member\x1a\x0c\x63ommon.proto\"j\n\"GuildMemberParametersChangeRequest\x12\x11\n\tmember_id\x18\x01 \x01(\x03\x12\x0f\n\x07rank_id\x18\x02 \x01(\x05\x12 \n\x18\x65xperience_given_percent\x18\x03 \x01(\x05\")\n\'GuildMemberWarnOnConnectionStartRequest\"(\n&GuildMemberWarnOnConnectionStopRequest\"A\n\x1cGuildMemberOnlineStatusEvent\x12\x11\n\tmember_id\x18\x01 \x01(\x03\x12\x0e\n\x06online\x18\x02 \x01(\x08\"]\n\x11GuildMembersEvent\x12H\n\x07members\x18\x01 \x03(\x0b\x32\x37.com.ankama.dofus.server.game.protocol.common.Character\"a\n\x16GuildMemberUpdateEvent\x12G\n\x06member\x18\x01 \x01(\x0b\x32\x37.com.ankama.dofus.server.game.protocol.common.Character\":\n\x15GuildMemberLeaveEvent\x12\x0e\n\x06kicked\x18\x01 \x01(\x08\x12\x11\n\tplayer_id\x18\x02 \x01(\x03\"\x10\n\x0eGuildLeftEvent\"\x82\x01\n\x14GuildMembershipEvent\x12Y\n\x11guild_information\x18\x01 \x01(\x0b\x32>.com.ankama.dofus.server.game.protocol.common.GuildInformation\x12\x0f\n\x07rank_id\x18\x02 \x01(\x05\"~\n\x10GuildJoinedEvent\x12Y\n\x11guild_information\x18\x01 \x01(\x0b\x32>.com.ankama.dofus.server.game.protocol.common.GuildInformation\x12\x0f\n\x07rank_id\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guild_member_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GUILDMEMBERPARAMETERSCHANGEREQUEST']._serialized_start=88
  _globals['_GUILDMEMBERPARAMETERSCHANGEREQUEST']._serialized_end=194
  _globals['_GUILDMEMBERWARNONCONNECTIONSTARTREQUEST']._serialized_start=196
  _globals['_GUILDMEMBERWARNONCONNECTIONSTARTREQUEST']._serialized_end=237
  _globals['_GUILDMEMBERWARNONCONNECTIONSTOPREQUEST']._serialized_start=239
  _globals['_GUILDMEMBERWARNONCONNECTIONSTOPREQUEST']._serialized_end=279
  _globals['_GUILDMEMBERONLINESTATUSEVENT']._serialized_start=281
  _globals['_GUILDMEMBERONLINESTATUSEVENT']._serialized_end=346
  _globals['_GUILDMEMBERSEVENT']._serialized_start=348
  _globals['_GUILDMEMBERSEVENT']._serialized_end=441
  _globals['_GUILDMEMBERUPDATEEVENT']._serialized_start=443
  _globals['_GUILDMEMBERUPDATEEVENT']._serialized_end=540
  _globals['_GUILDMEMBERLEAVEEVENT']._serialized_start=542
  _globals['_GUILDMEMBERLEAVEEVENT']._serialized_end=600
  _globals['_GUILDLEFTEVENT']._serialized_start=602
  _globals['_GUILDLEFTEVENT']._serialized_end=618
  _globals['_GUILDMEMBERSHIPEVENT']._serialized_start=621
  _globals['_GUILDMEMBERSHIPEVENT']._serialized_end=751
  _globals['_GUILDJOINEDEVENT']._serialized_start=753
  _globals['_GUILDJOINEDEVENT']._serialized_end=879
# @@protoc_insertion_point(module_scope)
