# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: guild_recruitment.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'guild_recruitment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17guild_recruitment.proto\x12\x37\x63om.ankama.dofus.server.game.protocol.guild.recruitment\x1a\x0c\x63ommon.proto\"\x7f\n\x1dGuildRecruitmentUpdateRequest\x12^\n\x0brecruitment\x18\x01 \x01(\x0b\x32I.com.ankama.dofus.server.game.protocol.common.GuildRecruitmentInformation\"w\n\x15GuildRecruitmentEvent\x12^\n\x0brecruitment\x18\x01 \x01(\x0b\x32I.com.ankama.dofus.server.game.protocol.common.GuildRecruitmentInformation\"!\n\x1fGuildRecruitmentInvalidateEventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guild_recruitment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GUILDRECRUITMENTUPDATEREQUEST']._serialized_start=98
  _globals['_GUILDRECRUITMENTUPDATEREQUEST']._serialized_end=225
  _globals['_GUILDRECRUITMENTEVENT']._serialized_start=227
  _globals['_GUILDRECRUITMENTEVENT']._serialized_end=346
  _globals['_GUILDRECRUITMENTINVALIDATEEVENT']._serialized_start=348
  _globals['_GUILDRECRUITMENTINVALIDATEEVENT']._serialized_end=381
# @@protoc_insertion_point(module_scope)
