# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: suggestion.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'suggestion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10suggestion.proto\x12\x30\x63om.ankama.dofus.server.game.protocol.suggestion\"\x87\x01\n\x1a\x41\x63tivitySuggestionsRequest\x12\x11\n\tmin_level\x18\x01 \x01(\x05\x12\x11\n\tmax_level\x18\x02 \x01(\x05\x12\x0f\n\x07\x61rea_id\x18\x03 \x01(\x05\x12\x1c\n\x14\x61\x63tivity_category_id\x18\x04 \x01(\x05\x12\x14\n\x0c\x63\x61rds_number\x18\x05 \x01(\x05\"*\n\x13\x41\x63tivityHideRequest\x12\x13\n\x0b\x61\x63tivity_id\x18\x01 \x01(\x05\"*\n\x13\x41\x63tivityLockRequest\x12\x13\n\x0b\x61\x63tivity_id\x18\x01 \x01(\x05\"R\n\x18\x41\x63tivitySuggestionsEvent\x12\x19\n\x11locked_activities\x18\x01 \x03(\x05\x12\x1b\n\x13unlocked_activities\x18\x02 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIVITYSUGGESTIONSREQUEST']._serialized_start=71
  _globals['_ACTIVITYSUGGESTIONSREQUEST']._serialized_end=206
  _globals['_ACTIVITYHIDEREQUEST']._serialized_start=208
  _globals['_ACTIVITYHIDEREQUEST']._serialized_end=250
  _globals['_ACTIVITYLOCKREQUEST']._serialized_start=252
  _globals['_ACTIVITYLOCKREQUEST']._serialized_end=294
  _globals['_ACTIVITYSUGGESTIONSEVENT']._serialized_start=296
  _globals['_ACTIVITYSUGGESTIONSEVENT']._serialized_end=378
# @@protoc_insertion_point(module_scope)
