# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/ankama/dofus/server/game/protocol/finish/move.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'com/ankama/dofus/server/game/protocol/finish/move.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7com/ankama/dofus/server/game/protocol/finish/move.proto\x12\x31\x63om.ankama.dofus.server.game.protocol.finish.move\"\x14\n\x12\x46inishMovesRequest\"A\n\x14\x46inishMoveSetRequest\x12\x16\n\x0e\x66inish_move_id\x18\x01 \x01(\x05\x12\x11\n\teffective\x18\x02 \x01(\x08\"\xb1\x01\n\x10\x46inishMovesEvent\x12\x64\n\x0c\x66inish_moves\x18\x01 \x03(\x0b\x32N.com.ankama.dofus.server.game.protocol.finish.move.FinishMovesEvent.FinishMove\x1a\x37\n\nFinishMove\x12\x16\n\x0e\x66inish_move_id\x18\x01 \x01(\x05\x12\x11\n\teffective\x18\x02 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.ankama.dofus.server.game.protocol.finish.move_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FINISHMOVESREQUEST']._serialized_start=110
  _globals['_FINISHMOVESREQUEST']._serialized_end=130
  _globals['_FINISHMOVESETREQUEST']._serialized_start=132
  _globals['_FINISHMOVESETREQUEST']._serialized_end=197
  _globals['_FINISHMOVESEVENT']._serialized_start=200
  _globals['_FINISHMOVESEVENT']._serialized_end=377
  _globals['_FINISHMOVESEVENT_FINISHMOVE']._serialized_start=322
  _globals['_FINISHMOVESEVENT_FINISHMOVE']._serialized_end=377
# @@protoc_insertion_point(module_scope)
