# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/ankama/dofus/server/game/protocol/guild/house.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'com/ankama/dofus/server/game/protocol/guild/house.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.ankama.dofus.server.game.protocol import common_pb2 as com_dot_ankama_dot_dofus_dot_server_dot_game_dot_protocol_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7com/ankama/dofus/server/game/protocol/guild/house.proto\x12\x31\x63om.ankama.dofus.server.game.protocol.guild.house\x1a\x32\x63om/ankama/dofus/server/game/protocol/common.proto\"W\n\x10GuildHousesEvent\x12\x43\n\x06houses\x18\x01 \x03(\x0b\x32\x33.com.ankama.dofus.server.game.protocol.common.House\"[\n\x15GuildHouseUpdateEvent\x12\x42\n\x05house\x18\x01 \x01(\x0b\x32\x33.com.ankama.dofus.server.game.protocol.common.House\"S\n\x15GuildHouseRemoveEvent\x12\x10\n\x08house_id\x18\x01 \x01(\x05\x12\x13\n\x0binstance_id\x18\x02 \x01(\x05\x12\x13\n\x0bsecond_hand\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.ankama.dofus.server.game.protocol.guild.house_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GUILDHOUSESEVENT']._serialized_start=162
  _globals['_GUILDHOUSESEVENT']._serialized_end=249
  _globals['_GUILDHOUSEUPDATEEVENT']._serialized_start=251
  _globals['_GUILDHOUSEUPDATEEVENT']._serialized_end=342
  _globals['_GUILDHOUSEREMOVEEVENT']._serialized_start=344
  _globals['_GUILDHOUSEREMOVEEVENT']._serialized_end=427
# @@protoc_insertion_point(module_scope)
