# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/ankama/dofus/server/game/protocol/area.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'com/ankama/dofus/server/game/protocol/area.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0com/ankama/dofus/server/game/protocol/area.proto\x12*com.ankama.dofus.server.game.protocol.area\".\n\x16SubareaRewardRateEvent\x12\x14\n\x0csubarea_rate\x18\x01 \x01(\x05\"3\n\x1c\x41reaFightModifierUpdateEvent\x12\x13\n\x0bspell_pairs\x18\x01 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.ankama.dofus.server.game.protocol.area_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBAREAREWARDRATEEVENT']._serialized_start=96
  _globals['_SUBAREAREWARDRATEEVENT']._serialized_end=142
  _globals['_AREAFIGHTMODIFIERUPDATEEVENT']._serialized_start=144
  _globals['_AREAFIGHTMODIFIERUPDATEEVENT']._serialized_end=195
# @@protoc_insertion_point(module_scope)
