# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/ankama/dofus/server/game/protocol/atlas.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'com/ankama/dofus/server/game/protocol/atlas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.ankama.dofus.server.game.protocol import common_pb2 as com_dot_ankama_dot_dofus_dot_server_dot_game_dot_protocol_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1com/ankama/dofus/server/game/protocol/atlas.proto\x12+com.ankama.dofus.server.game.protocol.atlas\x1a\x32\x63om/ankama/dofus/server/game/protocol/common.proto\"[\n\x11\x43ompassResetEvent\x12\x46\n\x04type\x18\x01 \x01(\x0e\x32\x38.com.ankama.dofus.server.game.protocol.atlas.CompassType\"\xe4\x03\n\x12\x43ompassUpdateEvent\x12\x46\n\x04type\x18\x01 \x01(\x0e\x32\x38.com.ankama.dofus.server.game.protocol.atlas.CompassType\x12Q\n\x0b\x63oordinates\x18\x02 \x01(\x0b\x32<.com.ankama.dofus.server.game.protocol.common.MapCoordinates\x12\x63\n\x0cparty_member\x18\x03 \x01(\x0b\x32K.com.ankama.dofus.server.game.protocol.atlas.CompassUpdateEvent.PartyMemberH\x00\x12[\n\x08pvp_seek\x18\x04 \x01(\x0b\x32G.com.ankama.dofus.server.game.protocol.atlas.CompassUpdateEvent.PvpSeekH\x00\x1a\x30\n\x0bPartyMember\x12\x11\n\tmember_id\x18\x01 \x01(\x03\x12\x0e\n\x06\x61\x63tive\x18\x02 \x01(\x08\x1a\x31\n\x07PvpSeek\x12\x11\n\ttarget_id\x18\x01 \x01(\x03\x12\x13\n\x0btarget_name\x18\x02 \x01(\tB\x0c\n\ncomplement*I\n\x0b\x43ompassType\x12\n\n\x06SIMPLE\x10\x00\x12\n\n\x06SPOUSE\x10\x01\x12\t\n\x05PARTY\x10\x02\x12\x0c\n\x08PVP_SEEK\x10\x03\x12\t\n\x05QUEST\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.ankama.dofus.server.game.protocol.atlas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPASSTYPE']._serialized_start=730
  _globals['_COMPASSTYPE']._serialized_end=803
  _globals['_COMPASSRESETEVENT']._serialized_start=150
  _globals['_COMPASSRESETEVENT']._serialized_end=241
  _globals['_COMPASSUPDATEEVENT']._serialized_start=244
  _globals['_COMPASSUPDATEEVENT']._serialized_end=728
  _globals['_COMPASSUPDATEEVENT_PARTYMEMBER']._serialized_start=615
  _globals['_COMPASSUPDATEEVENT_PARTYMEMBER']._serialized_end=663
  _globals['_COMPASSUPDATEEVENT_PVPSEEK']._serialized_start=665
  _globals['_COMPASSUPDATEEVENT_PVPSEEK']._serialized_end=714
# @@protoc_insertion_point(module_scope)
