# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/ankama/dofus/server/game/protocol/context.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'com/ankama/dofus/server/game/protocol/context.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.ankama.dofus.server.game.protocol import common_pb2 as com_dot_ankama_dot_dofus_dot_server_dot_game_dot_protocol_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3com/ankama/dofus/server/game/protocol/context.proto\x12-com.ankama.dofus.server.game.protocol.context\x1a\x32\x63om/ankama/dofus/server/game/protocol/common.proto\"\x18\n\x16\x43ontextCreationRequest\"%\n\x13\x43ontextReadyRequest\x12\x0e\n\x06map_id\x18\x01 \x01(\x03\"\x14\n\x12\x43ontextQuitRequest\"\'\n\x12\x43ontextKickRequest\x12\x11\n\ttarget_id\x18\x01 \x01(\x03\"\"\n\x0fShowCellRequest\x12\x0f\n\x07\x63\x65ll_id\x18\x01 \x01(\x05\"\xa1\x01\n\x14\x43ontextCreationEvent\x12`\n\x07\x63ontext\x18\x01 \x01(\x0e\x32O.com.ankama.dofus.server.game.protocol.context.ContextCreationEvent.GameContext\"\'\n\x0bGameContext\x12\r\n\tROLE_PLAY\x10\x00\x12\t\n\x05\x46IGHT\x10\x01\"\x15\n\x13\x43ontextDestroyEvent\"/\n\x19\x43ontextRemoveElementEvent\x12\x12\n\nelement_id\x18\x01 \x01(\x03\"0\n\x1a\x43ontextRemoveElementsEvent\x12\x12\n\nelement_id\x18\x01 \x03(\x03\"z\n\x1d\x43ontextRefreshEntityLookEvent\x12\x11\n\tentity_id\x18\x01 \x01(\x03\x12\x46\n\x04look\x18\x02 \x01(\x0b\x32\x38.com.ankama.dofus.server.game.protocol.common.EntityLook\"q\n\x18\x45ntitiesDispositionEvent\x12U\n\x0c\x64ispositions\x18\x01 \x03(\x0b\x32?.com.ankama.dofus.server.game.protocol.common.EntityDisposition\"\x1d\n\x1b\x45ntityDispositionErrorEvent\"A\n\rMonsterBoosts\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08xp_boost\x18\x02 \x01(\x05\x12\x12\n\ndrop_boost\x18\x03 \x01(\x05\"\xc6\x01\n\x19RefreshMonsterBoostsEvent\x12T\n\x0emonster_boosts\x18\x01 \x03(\x0b\x32<.com.ankama.dofus.server.game.protocol.context.MonsterBoosts\x12S\n\rfamily_boosts\x18\x02 \x03(\x0b\x32<.com.ankama.dofus.server.game.protocol.context.MonsterBoosts\"3\n\rShowCellEvent\x12\x11\n\tsource_id\x18\x01 \x01(\x03\x12\x0f\n\x07\x63\x65ll_id\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.ankama.dofus.server.game.protocol.context_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTEXTCREATIONREQUEST']._serialized_start=154
  _globals['_CONTEXTCREATIONREQUEST']._serialized_end=178
  _globals['_CONTEXTREADYREQUEST']._serialized_start=180
  _globals['_CONTEXTREADYREQUEST']._serialized_end=217
  _globals['_CONTEXTQUITREQUEST']._serialized_start=219
  _globals['_CONTEXTQUITREQUEST']._serialized_end=239
  _globals['_CONTEXTKICKREQUEST']._serialized_start=241
  _globals['_CONTEXTKICKREQUEST']._serialized_end=280
  _globals['_SHOWCELLREQUEST']._serialized_start=282
  _globals['_SHOWCELLREQUEST']._serialized_end=316
  _globals['_CONTEXTCREATIONEVENT']._serialized_start=319
  _globals['_CONTEXTCREATIONEVENT']._serialized_end=480
  _globals['_CONTEXTCREATIONEVENT_GAMECONTEXT']._serialized_start=441
  _globals['_CONTEXTCREATIONEVENT_GAMECONTEXT']._serialized_end=480
  _globals['_CONTEXTDESTROYEVENT']._serialized_start=482
  _globals['_CONTEXTDESTROYEVENT']._serialized_end=503
  _globals['_CONTEXTREMOVEELEMENTEVENT']._serialized_start=505
  _globals['_CONTEXTREMOVEELEMENTEVENT']._serialized_end=552
  _globals['_CONTEXTREMOVEELEMENTSEVENT']._serialized_start=554
  _globals['_CONTEXTREMOVEELEMENTSEVENT']._serialized_end=602
  _globals['_CONTEXTREFRESHENTITYLOOKEVENT']._serialized_start=604
  _globals['_CONTEXTREFRESHENTITYLOOKEVENT']._serialized_end=726
  _globals['_ENTITIESDISPOSITIONEVENT']._serialized_start=728
  _globals['_ENTITIESDISPOSITIONEVENT']._serialized_end=841
  _globals['_ENTITYDISPOSITIONERROREVENT']._serialized_start=843
  _globals['_ENTITYDISPOSITIONERROREVENT']._serialized_end=872
  _globals['_MONSTERBOOSTS']._serialized_start=874
  _globals['_MONSTERBOOSTS']._serialized_end=939
  _globals['_REFRESHMONSTERBOOSTSEVENT']._serialized_start=942
  _globals['_REFRESHMONSTERBOOSTSEVENT']._serialized_end=1140
  _globals['_SHOWCELLEVENT']._serialized_start=1142
  _globals['_SHOWCELLEVENT']._serialized_end=1193
# @@protoc_insertion_point(module_scope)
