# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/ankama/dofus/server/game/protocol/document.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'com/ankama/dofus/server/game/protocol/document.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4com/ankama/dofus/server/game/protocol/document.proto\x12.com.ankama.dofus.server.game.protocol.document\"0\n\x19\x44ocumentReadingBeginEvent\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\x05\"(\n\x12OpenGuideBookEvent\x12\x12\n\narticle_id\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.ankama.dofus.server.game.protocol.document_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCUMENTREADINGBEGINEVENT']._serialized_start=104
  _globals['_DOCUMENTREADINGBEGINEVENT']._serialized_end=152
  _globals['_OPENGUIDEBOOKEVENT']._serialized_start=154
  _globals['_OPENGUIDEBOOKEVENT']._serialized_end=194
# @@protoc_insertion_point(module_scope)
