# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/ankama/dofus/server/game/protocol/haapi.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'com/ankama/dofus/server/game/protocol/haapi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1com/ankama/dofus/server/game/protocol/haapi.proto\x12+com.ankama.dofus.server.game.protocol.haapi\"\x13\n\x11HaapiTokenRequest\" \n\x0fHaapiTokenEvent\x12\r\n\x05token\x18\x01 \x01(\t\"\x1f\n\x1dHaapiAuthenticationErrorEvent\"(\n\x11HaapiSessionEvent\x12\x13\n\x0bsession_uid\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.ankama.dofus.server.game.protocol.haapi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HAAPITOKENREQUEST']._serialized_start=98
  _globals['_HAAPITOKENREQUEST']._serialized_end=117
  _globals['_HAAPITOKENEVENT']._serialized_start=119
  _globals['_HAAPITOKENEVENT']._serialized_end=151
  _globals['_HAAPIAUTHENTICATIONERROREVENT']._serialized_start=153
  _globals['_HAAPIAUTHENTICATIONERROREVENT']._serialized_end=184
  _globals['_HAAPISESSIONEVENT']._serialized_start=186
  _globals['_HAAPISESSIONEVENT']._serialized_end=226
# @@protoc_insertion_point(module_scope)
