# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/ankama/dofus/server/game/protocol/notification.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'com/ankama/dofus/server/game/protocol/notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8com/ankama/dofus/server/game/protocol/notification.proto\x12\x32\x63om.ankama.dofus.server.game.protocol.notification\".\n\x1dNotificationUpdateFlagRequest\x12\r\n\x05index\x18\x01 \x01(\x05\"\x1a\n\x18NotificationResetRequest\"#\n\x12NotificationsEvent\x12\r\n\x05\x66lags\x18\x01 \x03(\x05\"B\n\x11NotificationEvent\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nparameters\x18\x02 \x03(\t\x12\r\n\x05\x66orce\x18\x03 \x01(\x08\"%\n\x17RemoveNotificationEvent\x12\n\n\x02id\x18\x01 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.ankama.dofus.server.game.protocol.notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFICATIONUPDATEFLAGREQUEST']._serialized_start=112
  _globals['_NOTIFICATIONUPDATEFLAGREQUEST']._serialized_end=158
  _globals['_NOTIFICATIONRESETREQUEST']._serialized_start=160
  _globals['_NOTIFICATIONRESETREQUEST']._serialized_end=186
  _globals['_NOTIFICATIONSEVENT']._serialized_start=188
  _globals['_NOTIFICATIONSEVENT']._serialized_end=223
  _globals['_NOTIFICATIONEVENT']._serialized_start=225
  _globals['_NOTIFICATIONEVENT']._serialized_end=291
  _globals['_REMOVENOTIFICATIONEVENT']._serialized_start=293
  _globals['_REMOVENOTIFICATIONEVENT']._serialized_end=330
# @@protoc_insertion_point(module_scope)
