# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/ankama/dofus/server/game/protocol/prism.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'com/ankama/dofus/server/game/protocol/prism.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.ankama.dofus.server.game.protocol import common_pb2 as com_dot_ankama_dot_dofus_dot_server_dot_game_dot_protocol_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1com/ankama/dofus/server/game/protocol/prism.proto\x12+com.ankama.dofus.server.game.protocol.prism\x1a\x32\x63om/ankama/dofus/server/game/protocol/common.proto\"\x1b\n\x19PrismTeleportationRequest\"\x14\n\x12PrismAttackRequest\"\x16\n\x14PrismExchangeRequest\"\x15\n\x13PrismRecycleRequest\"~\n\x0ePrismListEvent\x12l\n\x1bprism_localized_information\x18\x01 \x03(\x0b\x32G.com.ankama.dofus.server.game.protocol.common.PrismLocalizedInformation\"\x85\x01\n\x15PrismAddOrUpdateEvent\x12l\n\x1bprism_localized_information\x18\x01 \x01(\x0b\x32G.com.ankama.dofus.server.game.protocol.common.PrismLocalizedInformation\"\x80\x01\n\x10PrismRemoveEvent\x12l\n\x1bprism_localized_information\x18\x01 \x01(\x0b\x32G.com.ankama.dofus.server.game.protocol.common.PrismLocalizedInformation\"\x82\x01\n\x12PrismAttackedEvent\x12l\n\x1bprism_localized_information\x18\x01 \x01(\x0b\x32G.com.ankama.dofus.server.game.protocol.common.PrismLocalizedInformation\"\xb5\x02\n\x16PrismAttackResultEvent\x12l\n\x1bprism_localized_information\x18\x01 \x01(\x0b\x32G.com.ankama.dofus.server.game.protocol.common.PrismLocalizedInformation\x12r\n\x13prism_attack_result\x18\x02 \x01(\x0e\x32U.com.ankama.dofus.server.game.protocol.prism.PrismAttackResultEvent.PrismAttackResult\"9\n\x11PrismAttackResult\x12\x11\n\rDEFENDERS_WIN\x10\x00\x12\x11\n\rATTACKERS_WIN\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.ankama.dofus.server.game.protocol.prism_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRISMTELEPORTATIONREQUEST']._serialized_start=150
  _globals['_PRISMTELEPORTATIONREQUEST']._serialized_end=177
  _globals['_PRISMATTACKREQUEST']._serialized_start=179
  _globals['_PRISMATTACKREQUEST']._serialized_end=199
  _globals['_PRISMEXCHANGEREQUEST']._serialized_start=201
  _globals['_PRISMEXCHANGEREQUEST']._serialized_end=223
  _globals['_PRISMRECYCLEREQUEST']._serialized_start=225
  _globals['_PRISMRECYCLEREQUEST']._serialized_end=246
  _globals['_PRISMLISTEVENT']._serialized_start=248
  _globals['_PRISMLISTEVENT']._serialized_end=374
  _globals['_PRISMADDORUPDATEEVENT']._serialized_start=377
  _globals['_PRISMADDORUPDATEEVENT']._serialized_end=510
  _globals['_PRISMREMOVEEVENT']._serialized_start=513
  _globals['_PRISMREMOVEEVENT']._serialized_end=641
  _globals['_PRISMATTACKEDEVENT']._serialized_start=644
  _globals['_PRISMATTACKEDEVENT']._serialized_end=774
  _globals['_PRISMATTACKRESULTEVENT']._serialized_start=777
  _globals['_PRISMATTACKRESULTEVENT']._serialized_end=1086
  _globals['_PRISMATTACKRESULTEVENT_PRISMATTACKRESULT']._serialized_start=1029
  _globals['_PRISMATTACKRESULTEVENT_PRISMATTACKRESULT']._serialized_end=1086
# @@protoc_insertion_point(module_scope)
