# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/ankama/dofus/server/game/protocol/security.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'com/ankama/dofus/server/game/protocol/security.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4com/ankama/dofus/server/game/protocol/security.proto\x12.com.ankama.dofus.server.game.protocol.security\"p\n\x10\x46ileCheckRequest\x12M\n\ncheck_type\x18\x01 \x01(\x0e\x32\x39.com.ankama.dofus.server.game.protocol.security.CheckType\x12\r\n\x05value\x18\x02 \x01(\t\"%\n\x10TrustStatusEvent\x12\x11\n\tcertified\x18\x01 \x01(\x08\"r\n\x0e\x46ileCheckEvent\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12M\n\ncheck_type\x18\x02 \x01(\x0e\x32\x39.com.ankama.dofus.server.game.protocol.security.CheckType*%\n\tCheckType\x12\n\n\x06LENGTH\x10\x00\x12\x0c\n\x08HASH_SUM\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.ankama.dofus.server.game.protocol.security_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKTYPE']._serialized_start=373
  _globals['_CHECKTYPE']._serialized_end=410
  _globals['_FILECHECKREQUEST']._serialized_start=104
  _globals['_FILECHECKREQUEST']._serialized_end=216
  _globals['_TRUSTSTATUSEVENT']._serialized_start=218
  _globals['_TRUSTSTATUSEVENT']._serialized_end=255
  _globals['_FILECHECKEVENT']._serialized_start=257
  _globals['_FILECHECKEVENT']._serialized_end=371
# @@protoc_insertion_point(module_scope)
