# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/ankama/dofus/server/game/protocol/symbiont.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'com/ankama/dofus/server/game/protocol/symbiont.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4com/ankama/dofus/server/game/protocol/symbiont.proto\x12.com.ankama.dofus.server.game.protocol.symbiont\"I\n\x1eWrapperObjectDissociateRequest\x12\x10\n\x08host_uid\x18\x01 \x01(\x05\x12\x15\n\rhost_position\x18\x02 \x01(\x05\"8\n\x0eMimicryRequest\x12\x14\n\x0csymbiont_uid\x18\x01 \x01(\x05\x12\x10\n\x08host_uid\x18\x02 \x01(\x05\"`\n\x0fMimicryResponse\x12M\n\x06result\x18\x01 \x01(\x0e\x32=.com.ankama.dofus.server.game.protocol.symbiont.MimicryResult\"&\n\x12MimicryFreeRequest\x12\x10\n\x08host_uid\x18\x01 \x01(\x05\"d\n\x13MimicryFreeResponse\x12M\n\x06result\x18\x01 \x01(\x0e\x32=.com.ankama.dofus.server.game.protocol.symbiont.MimicryResult*r\n\rMimicryResult\x12\t\n\x05\x45RROR\x10\x00\x12\x0f\n\x0bPLAYER_BUSY\x10\x01\x12\x17\n\x13HOST_NOT_MIMICKABLE\x10\x02\x12\x10\n\x0cHOST_WRAPPED\x10\x03\x12\r\n\tDUPLICATE\x10\x04\x12\x0b\n\x07SUCCESS\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.ankama.dofus.server.game.protocol.symbiont_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MIMICRYRESULT']._serialized_start=477
  _globals['_MIMICRYRESULT']._serialized_end=591
  _globals['_WRAPPEROBJECTDISSOCIATEREQUEST']._serialized_start=104
  _globals['_WRAPPEROBJECTDISSOCIATEREQUEST']._serialized_end=177
  _globals['_MIMICRYREQUEST']._serialized_start=179
  _globals['_MIMICRYREQUEST']._serialized_end=235
  _globals['_MIMICRYRESPONSE']._serialized_start=237
  _globals['_MIMICRYRESPONSE']._serialized_end=333
  _globals['_MIMICRYFREEREQUEST']._serialized_start=335
  _globals['_MIMICRYFREEREQUEST']._serialized_end=373
  _globals['_MIMICRYFREERESPONSE']._serialized_start=375
  _globals['_MIMICRYFREERESPONSE']._serialized_end=475
# @@protoc_insertion_point(module_scope)
